### ISSUE TITLE
24H2 checklist 

### ISSUE THREAD

**Issue by dmex** [winsiderss/systeminformer#2101]
### An inside look at Microsoft's development strategy for Windows 11:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/s99ZeamF7J0/0.jpg)](https://www.youtube.com/watch?v=s99ZeamF7J0)
https://www.youtube.com/watch?v=s99ZeamF7J0

Microsoft retuning null pointers for information classes has broken enumeration of handles, threads and other objects:

- [x] SystemModuleInformation (11) RTL_PROCESS_MODULE_INFORMATION RTL_PROCESS_MODULE_INFORMATION.DllBase
- [x] SystemLocksInformation (12) RTL_PROCESS_LOCK_INFORMATION RTL_PROCESS_LOCK_INFORMATION.Address
- [x] SystemHandleInformation (16) SYSTEM_HANDLE_INFORMATION SYSTEM_HANDLE_INFORMATION.Handles[N].Object
- [x] SystemObjectInformation (17)	SYSTEM_OBJECT_INFORMATION	SYSTEM_OBJECT_INFORMATION.Object
- [x] 	SystemExtendedHandleInformation (64) SYSTEM_HANDLE_INFORMATION_EX SYSTEM_HANDLE_INFORMATION_EX.Handles[N].Object
- [x] SystemBigPoolInformation (66) SYSTEM_BIGPOOL_INFORMATION	SYSTEM_BIGPOOL_INFORMATION.AllocationInfo[N].VirtualAddress
- [x] SystemModuleInformationEx (77) RTL_PROCESS_MODULE_INFORMATION_EX	RTL_PROCESS_MODULE_INFORMATION_EX.BaseInfo.ImageBase
- [x] SystemFullProcessInformation (148) SYSTEM_EXTENDED_THREAD_INFORMATION.StackBase
- [x] SYSTEM_EXTENDED_THREAD_INFORMATION.Win32StartAddress if the thread’s Win32StartAddress is a kernel address.
- [x] SYSTEM_EXTENDED_THREAD_INFORMATION.ThreadInfo.StartAddress
- [x] ProcessHandleTracing (32) PROCESS_HANDLE_TRACING_QUERY	PROCESS_HANDLE_TRACING_QUERY.HandleTrace[N].Stacks
- [x] ProcessWorkingSetWatchEx (42) PROCESS_WS_WATCH_INFORMATION_EX	
- [x] PROCESS_WS_WATCH_INFORMATION_EX.BasicInfo.FaultingPc
- [x] PROCESS_WS_WATCH_INFORMATION_EX.BasicInfo.FaultingVa

### Steps to reproduce (optional)

Windows 11 - https://windows-internals.com/kaslr-leaks-restriction/

### Expected behavior (optional)

Functional

### Actual behavior (optional)

Non-functional

### Environment (optional)

![image](https://github.com/winsiderss/systeminformer/assets/1306177/8600d05f-46d6-4790-a064-d5e1a4f89716)

**Comment by dmex** [comment]
![image](https://github.com/user-attachments/assets/0785d84f-8da4-4da9-b6d3-f90946f95224)

**Comment by MagicAndre1981** [comment]
I liked Vista 😇 and was using it as main system since Build 5456. And in Vista Windows Error reporting showed in which build/update my issues were fixed

![https://www.wictorwilen.se/blog/introduction-to-vista-problem-reports-and-solutions/](https://github.com/user-attachments/assets/c7d6391d-2284-4158-a126-bee2f766d636)

I would like to see this again in Windows 10/11.

My test VM with latest ESU updates 6.0.6003 runs fine, here you see how fast Explorer was, not like today with 11 and the XAML integration since 23H2.
